### ISSUE TITLE
Open Source this repository

### ISSUE THREAD

**Issue by rmehner** [eHealthAfrica/angular-eha.login-service#3]
@remy can you please squash the commits to one, so we can review this and make it open source? It's included as dependency in some repos and would ease our setup :)

Thanks!

**Comment by rmehner** [comment]
Squashed everything, now @karlwestin and me will do the review and then open source this.

**Comment by rmehner** [comment]
review done, no credentials as far as I can see :+1:

**Comment by karlwestin** [comment]
looks good to me

**Comment by tlvince** [comment]
Now opened.
